name: Deploy Hugo site

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  VERSION: '4.2'
  HUGO: '0.131.0'
  PAGEFIND: '1.1.0'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    permissions:
      id-token: write
      pages: write

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.temp }}/hugo.deb
            ${{ runner.temp }}/hugo_cache
            ./resources

          key: ${{ github.workflow }}-${{ github.ref }}-${{ env.VERSION }}-${{ env.HUGO }}-${{ github.run_id }}
          restore-keys: |
            ${{ github.workflow }}-${{ github.ref }}-${{ env.VERSION }}-${{ env.HUGO }}-

      - name: Install Hugo CLI
        run: >
          [[ -f ${{ runner.temp }}/hugo.deb ]]
          || wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO }}/hugo_extended_${{ env.HUGO }}_linux-amd64.deb
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install pagefind CLI
        run: >
          [[ -f ${{ runner.temp }}/pagefind.tar.xz ]]
          || wget -O ${{ runner.temp }}/pagefind.tar.xz https://github.com/CloudCannon/pagefind/releases/download/v${{ env.HUGO }}/pagefind-v${{ env.PAGEFIND }}-x86_64-unknown-linux-musl.tar.gz
          && tar -xJf ${{ runner.temp }}/pagefind.tar.xz
          && sudo cp -r ${{ runner.temp }}/pagefind/* /usr/local

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build site
        run: >
          hugo
          --baseURL "${{ steps.pages.outputs.base_url }}/"
          --cacheDir ${{ runner.temp }}/hugo_cache
          --enableGitInfo
          --gc
          --minify

      - name: Build search
        run: >
          pagefind 
          --site public

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: Deploy to Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2

    timeout-minutes: 15
